// All Jagadhatri Puja pandals. Add, edit, or remove entries freely.
export const PANDALS = [
// ── Chandannagar ──
{id:"bagbazar",name:"Bagbazar Sarbojanin",area:"Chandannagar",address:"Bagbazar, Chandannagar",lat:22.8680,lng:88.3710,timings:"10 AM – 10 PM",theme:"Grand idol and lighting"},
{id:"barabazar",name:"Barabazar Sarbojanin",area:"Chandannagar",address:"Barabazar, Chandannagar",lat:22.8660,lng:88.3690,timings:"10 AM – 10 PM",theme:"Opulent pandal + street food"},
{id:"chaulpatty",name:"Chaulpatty Adi Maa",area:"Chandannagar",address:"Lakshmiganj Bazar",lat:22.8640,lng:88.3620,timings:"10 AM – 10 PM",theme:"300-year-old traditional puja"},
{id:"tematha-ranima",name:"Tematha Ranima",area:"Chandannagar",address:"Tematha",lat:22.8650,lng:88.3600,timings:"10 AM – 10 PM",theme:"Tallest Rani Ma idol"},
{id:"subhaspally",name:"Subhaspally Sarbojanin",area:"Chandannagar",address:"Near Chandannagar Station",lat:22.8665,lng:88.3680,timings:"10 AM – 10 PM",theme:"Innovative pandal art"},
{id:"palpara",name:"Palpara Sarbojanin",area:"Chandannagar",address:"Palpara",lat:22.87145,lng:88.36923,timings:"10 AM – 10 PM",theme:"81-year-old legendary puja"},
{id:"helapukur",name:"Helapukur Jagaddhatri Committee",area:"Chandannagar",address:"Helapukur Rd, Sarishapara",lat:22.8670,lng:88.3730,timings:"10 AM – 10 PM",theme:"Diamond-studded idol"},
{id:"niyogibagan",name:"Niyogi Bagan",area:"Chandannagar",address:"Niyogi Bagan",lat:22.8590,lng:88.3640,timings:"10 AM – 10 PM",theme:"Round-shaped pandal"},
{id:"mahadanga",name:"Mahadanga Main Road",area:"Chandannagar",address:"Mahadanga",lat:22.8610,lng:88.3670,timings:"10 AM – 10 PM",theme:"Terracotta art of West Bengal"},
{id:"kanailal",name:"Kanailal Pally",area:"Chandannagar",address:"Kanailal Pally",lat:22.8600,lng:88.3660,timings:"10 AM – 10 PM",theme:"World's biggest Jagadhatri idol"},
{id:"bibirhat",name:"Bibirhat Charaktala Tematha",area:"Chandannagar",address:"Palpara Rd, Taldanga",lat:22.87811,lng:88.37360,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"tantirbagan",name:"Tantirbagan Sarbajanin",area:"Chandannagar",address:"Sarishapara",lat:22.86756,lng:88.37288,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"suksanatantala",name:"Suksanatantala Benepukurdhar",area:"Chandannagar",address:"1st Ln, Sukhsanatantala",lat:22.86096,lng:88.36024,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"lalbagan",name:"Lalbagan Sarbajanin",area:"Chandannagar",address:"Durga Charan Rakshit Rd",lat:22.8590,lng:88.3580,timings:"10 AM – 10 PM",theme:"Vibrant celebration"},
{id:"madhyanchal",name:"Madhyanchal Sarbajanin",area:"Chandannagar",address:"Station Rd, Sukhsanatantala",lat:22.8580,lng:88.3570,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"kundughat",name:"Kundughat Sarbajanin",area:"Chandannagar",address:"Sarishapara, Nikaripara",lat:22.87152,lng:88.37906,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"lalbagan-padripara",name:"Lalbagan Padripara",area:"Chandannagar",address:"Sukhsanatantala",lat:22.8585,lng:88.3585,timings:"10 AM – 10 PM",theme:"Cherished tradition"},
{id:"padripara-farmadighi",name:"Padripara Farmadighi Sarbajanin",area:"Chandannagar",address:"Farmadighirdhar Local Rd",lat:22.85622,lng:88.36655,timings:"10 AM – 10 PM",theme:"Architectural masterpiece"},
{id:"boro-mitra",name:"Boro Mitrabagan Sarbajanin",area:"Chandannagar",address:"Boro Mitra Bagan",lat:22.87575,lng:88.37429,timings:"10 AM – 10 PM",theme:"Intricate illumination"},
{id:"balak-sampraday",name:"Balak Sampraday Ganj Neogi Bagan",area:"Chandannagar",address:"Sarishapara",lat:22.8660,lng:88.3730,timings:"10 AM – 10 PM",theme:"Testament to faith"},
{id:"dinemardanga",name:"Dinemardanga Amtala Sarbajanin",area:"Chandannagar",address:"Dinemardanga",lat:22.8620,lng:88.3650,timings:"10 AM – 10 PM",theme:"Faith, artistry, unity"},
{id:"duplexpatty",name:"Duplexpatty Kultala Sarbajanin",area:"Chandannagar",address:"Narua Dharmarajtala",lat:22.8595,lng:88.3595,timings:"10 AM – 10 PM",theme:"Revered name"},
{id:"sramikpally",name:"Sramikpally Laldighir Dhar",area:"Chandannagar",address:"Sramikpally",lat:22.8580,lng:88.3560,timings:"10 AM – 10 PM",theme:"Faith meets artistry"},
{id:"surighat",name:"Surighat Sarbajanin",area:"Chandannagar",address:"Sarishapara",lat:22.8660,lng:88.3740,timings:"10 AM – 10 PM",theme:"Dazzling lights & grand idol"},
{id:"kantapukur",name:"Kantapukur Sarbajanin",area:"Chandannagar",address:"Kantapukur Main Rd",lat:22.87593,lng:88.36763,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"milannagar",name:"Milannagar Sohid Bedi",area:"Chandannagar",address:"Uttarpara, Mahadanga Colony",lat:22.8560,lng:88.3650,timings:"10 AM – 10 PM",theme:"Legacy since 1686"},
{id:"beshohata",name:"Beshohata Sarbajanin",area:"Chandannagar",address:"Kabi Bharat Chandra Rd",lat:22.8530,lng:88.3620,timings:"10 AM – 10 PM",theme:"Beloved committee"},
{id:"chandni-benepukur",name:"Chandni Benepukur Sarbajanin",area:"Chandannagar",address:"Fatokgora, Last French Colony",lat:22.8700,lng:88.3760,timings:"10 AM – 10 PM",theme:"Celebrated committee"},
{id:"talpukurdhar-sishu",name:"Talpukurdhar Sishu Udyan",area:"Chandannagar",address:"Fatokgora",lat:22.8705,lng:88.3765,timings:"10 AM – 10 PM",theme:"Celebrated committee"},
{id:"sabinara",name:"Sabinara Sarbajanin",area:"Chandannagar",address:"Sabinara",lat:22.8650,lng:88.3700,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"bagbazar-talpukurdhar",name:"Bagbazar Talpukurdhar",area:"Chandannagar",address:"Bagbazar",lat:22.8685,lng:88.3715,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"barasat-gate",name:"Barasat Gate",area:"Chandannagar",address:"Barasat Gate",lat:22.8700,lng:88.3800,timings:"10 AM – 10 PM",theme:"Platinum Jubilee"},
{id:"boraichanditala",name:"Boraichanditala",area:"Chandannagar",address:"Boraichanditala",lat:22.8620,lng:88.3680,timings:"10 AM – 10 PM",theme:"Golden Jubilee"},
{id:"subhas-jagaran",name:"Subhas Jagaran Sangha, Tematha",area:"Chandannagar",address:"Tematha",lat:22.8655,lng:88.3610,timings:"10 AM – 10 PM",theme:"Diamond Jubilee"},
{id:"hatkhola-mansatala",name:"Hatkhola Mansatala",area:"Chandannagar",address:"Hatkhola",lat:22.8540,lng:88.3620,timings:"10 AM – 10 PM",theme:"Diamond Jubilee"},
{id:"narua-sarkarpara",name:"Narua Sarkarpara",area:"Chandannagar",address:"Narua",lat:22.8500,lng:88.3550,timings:"10 AM – 10 PM",theme:"Centennial Jubilee"},
{id:"narua-boropukurdhar",name:"Narua Boropukurdhar",area:"Chandannagar",address:"Narua",lat:22.8505,lng:88.3555,timings:"10 AM – 10 PM",theme:"Platinum Jubilee"},
{id:"bagbazar-chowmatha",name:"Bagbazar Chowmatha",area:"Chandannagar",address:"Bagbazar",lat:22.8680,lng:88.3720,timings:"10 AM – 10 PM",theme:"Diamond Jubilee"},
{id:"urdibazar",name:"Urdibazar",area:"Chandannagar",address:"Urdibazar",lat:22.8670,lng:88.3700,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"doibakpara",name:"Doibakpara",area:"Chandannagar",address:"Doibakpara",lat:22.8630,lng:88.3670,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"talpukur-dhar",name:"Talpukur Dhar",area:"Chandannagar",address:"Talpukur",lat:22.8660,lng:88.3720,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"doshobhuja-tala",name:"Doshobhuja Tala",area:"Chandannagar",address:"Doshobhuja Tala",lat:22.8640,lng:88.3690,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"gondalpara-chd",name:"Gondalpara A. C. Chatterjee Lane",area:"Chandannagar",address:"Gondalpara",lat:22.8620,lng:88.3660,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"mansatala",name:"Mansatala",area:"Chandannagar",address:"Mansatala",lat:22.8600,lng:88.3640,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"boro-bazar",name:"Boro Bazar",area:"Chandannagar",address:"Boro Bazar",lat:22.8660,lng:88.3690,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"mitra-bari",name:"Mitra Bari",area:"Chandannagar",address:"Khalisani",lat:22.8600,lng:88.3700,timings:"Morning & Evening",theme:"Historic family puja"},
{id:"ghosh-bari",name:"Ghosh Bari",area:"Chandannagar",address:"Fatakgora",lat:22.8650,lng:88.3750,timings:"Morning & Evening",theme:"Historic family puja"},
{id:"pal-bari",name:"Pal Bari",area:"Chandannagar",address:"Surerpukur",lat:22.8700,lng:88.3650,timings:"Morning & Evening",theme:"Historic family puja"},
{id:"chandannagar-central",name:"Chandannagar Central Committee",area:"Chandannagar",address:"Central Chandannagar",lat:22.8650,lng:88.3680,timings:"10 AM – 10 PM",theme:"Central committee"},
{id:"fatakgora",name:"Fatakgora Sarbajanin",area:"Chandannagar",address:"Fatakgora",lat:22.8710,lng:88.3770,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"last-french-colony",name:"Last French Colony Sarbajanin",area:"Chandannagar",address:"Last French Colony",lat:22.8708,lng:88.3768,timings:"10 AM – 10 PM",theme:"Heritage theme"},
{id:"sarishapara-nikaripara",name:"Sarishapara Nikaripara",area:"Chandannagar",address:"Sarishapara",lat:22.8710,lng:88.3785,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"goswamipara",name:"Goswamipara Sarbajanin",area:"Chandannagar",address:"Goswamipara",lat:22.8645,lng:88.3665,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"khalisani",name:"Khalisani Sarbajanin",area:"Chandannagar",address:"Khalisani",lat:22.8598,lng:88.3705,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"burrabazar-chowk",name:"Burrabazar Chowk",area:"Chandannagar",address:"Burrabazar",lat:22.8668,lng:88.3695,timings:"10 AM – 10 PM",theme:"Market-area puja"},
{id:"college-road",name:"College Road Sarbajanin",area:"Chandannagar",address:"College Road",lat:22.8630,lng:88.3695,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"riverside-ghat",name:"Riverside Ghat Committee",area:"Chandannagar",address:"Strand Road",lat:22.8625,lng:88.3625,timings:"10 AM – 10 PM",theme:"Riverside pandal"},
{id:"lichubagan",name:"Lichubagan Sarbajanin",area:"Chandannagar",address:"Lichubagan",lat:22.8570,lng:88.3620,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"kalitala",name:"Kalitala Sarbajanin",area:"Chandannagar",address:"Kalitala",lat:22.8615,lng:88.3645,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"natun-bazar",name:"Natun Bazar",area:"Chandannagar",address:"Natun Bazar",lat:22.8655,lng:88.3675,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"station-road-chd",name:"Station Road Sarbajanin",area:"Chandannagar",address:"Station Road",lat:22.8668,lng:88.3688,timings:"10 AM – 10 PM",theme:"Near Chandannagar station"},

// ── Mankundu ──
{id:"mankundu-sporting",name:"Mankundu Sporting Club",area:"Mankundu",address:"Mankundu",lat:22.8577,lng:88.3652,timings:"10 AM – 10 PM",theme:"Dynamic rituals, community feasts"},
{id:"circus-math",name:"Circus Math",area:"Mankundu",address:"Circus Math",lat:22.8580,lng:88.3650,timings:"10 AM – 10 PM",theme:"Towering pandal"},
{id:"charabagan",name:"Charabagan Balak Sangha",area:"Mankundu",address:"Mankundu Station Rd, Pirtala",lat:22.8570,lng:88.3640,timings:"10 AM – 10 PM",theme:"Towering heights"},
{id:"natunpara",name:"Natunpara",area:"Mankundu",address:"Natunpara",lat:22.8585,lng:88.3660,timings:"10 AM – 10 PM",theme:"Moner Manush"},
{id:"mankundu-notunpara",name:"Mankundu Notunpara",area:"Mankundu",address:"Notunpara",lat:22.8590,lng:88.3670,timings:"10 AM – 10 PM",theme:"Rural life structures"},
{id:"moran-road",name:"Moran Road",area:"Mankundu",address:"Moran Road",lat:22.8560,lng:88.3630,timings:"10 AM – 10 PM",theme:"Katputli theme"},
{id:"lichutola",name:"Lichutola",area:"Mankundu",address:"Lichutola",lat:22.8550,lng:88.3620,timings:"10 AM – 10 PM",theme:"Unique deity face"},
{id:"hatkhola-daibokpara",name:"Hatkhola Daibokpara",area:"Mankundu",address:"Hatkhola, Daibokpara",lat:22.8540,lng:88.3610,timings:"10 AM – 10 PM",theme:"Popular 2023 pandal"},
{id:"panchanontola",name:"Panchanontola",area:"Mankundu",address:"Panchanontola",lat:22.8530,lng:88.3600,timings:"10 AM – 10 PM",theme:"Royal theme"},
{id:"hatkhola-monshatola",name:"Hatkhola Monshatola",area:"Mankundu",address:"Hatkhola",lat:22.8520,lng:88.3590,timings:"10 AM – 10 PM",theme:"Unique structures"},
{id:"harerpukur",name:"Harerpukurdhar Sarbajanin",area:"Mankundu",address:"Telinipara",lat:22.84254,lng:88.36331,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"gondalpara-mkd",name:"Gondalpara A. C. Chatterjee Lane",area:"Mankundu",address:"Telinipara",lat:22.84242,lng:88.36821,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"mohila-samity",name:"Mohila Samity Sarbajanin",area:"Mankundu",address:"Mahadanga Colony",lat:22.8560,lng:88.3640,timings:"10 AM – 10 PM",theme:"Esteemed committee"},
{id:"dinemardanga-pancha",name:"Dinemardanga Panchapandab",area:"Mankundu",address:"Telinipara",lat:22.8420,lng:88.3630,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"milannagar-mkd",name:"Milannagar Sohid Bedi",area:"Mankundu",address:"Uttarpara",lat:22.8560,lng:88.3650,timings:"10 AM – 10 PM",theme:"Legacy since 1686"},
{id:"beshohata-mkd",name:"Beshohata Sarbajanin",area:"Mankundu",address:"Kabi Bharat Chandra Rd",lat:22.8530,lng:88.3620,timings:"10 AM – 10 PM",theme:"Beloved committee"},
{id:"telinipara",name:"Telinipara Sarbajanin",area:"Mankundu",address:"Telinipara",lat:22.8426,lng:88.3640,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"pirtala",name:"Pirtala Sarbajanin",area:"Mankundu",address:"Pirtala",lat:22.8572,lng:88.3645,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"mankundu-bazar",name:"Mankundu Bazar Committee",area:"Mankundu",address:"Mankundu Bazar",lat:22.8578,lng:88.3660,timings:"10 AM – 10 PM",theme:"Bazar-area puja"},
{id:"mankundu-station-road",name:"Mankundu Station Road",area:"Mankundu",address:"Mankundu Station Road",lat:22.8568,lng:88.3638,timings:"10 AM – 10 PM",theme:"Near Mankundu station"},

// ── Bhadreswar ──
{id:"brahminpara",name:"Brahminpara Jagarani Samity",area:"Bhadreswar",address:"Brahminpara",lat:22.8500,lng:88.3400,timings:"10 AM – 10 PM",theme:"Silver Jubilee"},
{id:"swetpur",name:"Swetpur Sarbajanin",area:"Bhadreswar",address:"Bhola Rd, Nowapara",lat:22.85332,lng:88.32169,timings:"10 AM – 10 PM",theme:"Beacon of creativity"},
{id:"puroshree",name:"Puroshree Sarbajanin",area:"Bhadreswar",address:"Purasree More",lat:22.8500,lng:88.3300,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"bhadreswar-station",name:"Bhadreswar Station Chowmatha",area:"Bhadreswar",address:"Station Road",lat:22.8480,lng:88.3380,timings:"10 AM – 10 PM",theme:"Golden Jubilee"},
{id:"bhadreswar-byabsayi",name:"Bhadreshwar Byabsayi Samity",area:"Bhadreswar",address:"Swami Abhayananda Ln",lat:22.8490,lng:88.3390,timings:"10 AM – 10 PM",theme:"Breathtaking pandal"},
{id:"bhadreswar-sporting",name:"Bhadreswar Jagadhatri Sporting Club",area:"Bhadreswar",address:"Bhadreswar",lat:22.8495,lng:88.3420,timings:"10 AM – 10 PM",theme:"Architectural masterpiece"},
{id:"nowapara",name:"Nowapara Sarbajanin",area:"Bhadreswar",address:"Nowapara",lat:22.8520,lng:88.3250,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"bhadreswar-ghat",name:"Bhadreswar Ghat Committee",area:"Bhadreswar",address:"Riverbank",lat:22.8470,lng:88.3430,timings:"10 AM – 10 PM",theme:"Riverside pandal"},
{id:"bhadreswar-bazar",name:"Bhadreswar Bazar",area:"Bhadreswar",address:"Bhadreswar Bazar",lat:22.8485,lng:88.3405,timings:"10 AM – 10 PM",theme:"Traditional"},
{id:"rathtala-bhadreswar",name:"Rathtala Sarbajanin",area:"Bhadreswar",address:"Rathtala",lat:22.8510,lng:88.3370,timings:"10 AM – 10 PM",theme:"Traditional"},

// ── Kolkata ──
{id:"baubazar-kolkata",name:"Baubazar Jagadhatri Puja",area:"Kolkata",address:"Near Santosh Mitra Square",lat:22.5726,lng:88.3639,timings:"Morning & Evening",theme:"Bonedi Bari tradition"},
{id:"shobhabazar-rajbari",name:"Shobhabazar Rajbari",area:"Kolkata",address:"Shobhabazar",lat:22.5850,lng:88.3650,timings:"Morning & Evening",theme:"Bindhyabasini form, peacock dance"},
{id:"madan-gopal-dey",name:"Madan Gopal Dey's Family",area:"Kolkata",address:"North Kolkata",lat:22.5700,lng:88.3600,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"thanthania-dey",name:"Thanthania Dey Barir Puja",area:"Kolkata",address:"Thanthania",lat:22.5750,lng:88.3620,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"chorbagan-maitra",name:"Chorbagan Maitra Bati",area:"Kolkata",address:"Chorbagan",lat:22.5800,lng:88.3600,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"batakrishna-pal",name:"Batakrishna Pal's Jagadhatri Puja",area:"Kolkata",address:"North Kolkata",lat:22.5720,lng:88.3580,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"amritlal-dawn",name:"Amritlal Dawn House",area:"Kolkata",address:"North Kolkata",lat:22.5780,lng:88.3610,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"chatu-babu",name:"Chatu Babu Latu Babu's Puja",area:"Kolkata",address:"North Kolkata",lat:22.5820,lng:88.3640,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"karmakar-family",name:"Karmakar Family Temple",area:"Kolkata",address:"North Kolkata",lat:22.5760,lng:88.3630,timings:"Morning & Evening",theme:"Established 1298 BS"},
{id:"dey-bari",name:"Dey Bari",area:"Kolkata",address:"North Kolkata",lat:22.5740,lng:88.3615,timings:"Morning & Evening",theme:"Bonedi Bari"},
{id:"maitra-bati",name:"Maitra Bati",area:"Kolkata",address:"North Kolkata",lat:22.5770,lng:88.3625,timings:"Morning & Evening",theme:"Bonedi Bari"},

// ── Krishnanagar ──
{id:"burima",name:"Burima of Chasa Para",area:"Krishnanagar",address:"Chasa Para",lat:23.4000,lng:88.5000,timings:"10 AM – 10 PM",theme:"Tirupathi of Krishnanagar (est. 1772)"},
{id:"choto-maa",name:"Choto Maa of Kathalpota Barowari",area:"Krishnanagar",address:"Kathalpota",lat:23.4010,lng:88.5010,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"mejo-maa",name:"Mejo Maa of College Street Barowari",area:"Krishnanagar",address:"College Street",lat:23.4020,lng:88.5020,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"maa-jaleswari",name:"Maa Jaleswari of Malo Para",area:"Krishnanagar",address:"Malo Para",lat:23.4030,lng:88.5030,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"raj-rajeshwary",name:"Raj Rajeshwary Jagaddhatri Puja",area:"Krishnanagar",address:"Krishnanagar",lat:23.4040,lng:88.5040,timings:"10 AM – 10 PM",theme:"Royal heritage"},
{id:"krishnanagar-rajbari",name:"Krishnanagar Rajbari Puja",area:"Krishnanagar",address:"Rajbari",lat:23.4050,lng:88.5050,timings:"10 AM – 10 PM",theme:"Royal tradition"},
{id:"patra-bazar",name:"Patra Bazar Swikriti Club",area:"Krishnanagar",address:"Patra Bazar",lat:23.4060,lng:88.5060,timings:"10 AM – 10 PM",theme:"Popular club"},
{id:"boubazar-barowari",name:"Boubazar Barowari",area:"Krishnanagar",address:"Boubazar",lat:23.4070,lng:88.5070,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"raypara-malipara",name:"Raypara Malipara Barowari",area:"Krishnanagar",address:"Raypara Malipara",lat:23.4080,lng:88.5080,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"ghurni-daspara",name:"Ghurni Daspara Barowari",area:"Krishnanagar",address:"Ghurni Daspara",lat:23.4090,lng:88.5090,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"shibtala",name:"Shibtala Barowari",area:"Krishnanagar",address:"Shibtala",lat:23.4100,lng:88.5100,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"kalinagar-rainbow",name:"Kalinagar Rainbow Club",area:"Krishnanagar",address:"Kalinagar",lat:23.4110,lng:88.5110,timings:"10 AM – 10 PM",theme:"Popular club"},
{id:"shaktinagar",name:"Shaktinagar Panchmatha More",area:"Krishnanagar",address:"Shaktinagar",lat:23.4120,lng:88.5120,timings:"10 AM – 10 PM",theme:"Historic barowari"},
{id:"chowdhury-para",name:"Chowdhury Para Barowari",area:"Krishnanagar",address:"Chowdhury Para",lat:23.4130,lng:88.5130,timings:"10 AM – 10 PM",theme:"Near station"},
{id:"panchmatha-more",name:"Panchmatha More Barowari",area:"Krishnanagar",address:"Panchmatha More",lat:23.4140,lng:88.5140,timings:"10 AM – 10 PM",theme:"Popular"},
{id:"pallishree",name:"Pallishree",area:"Krishnanagar",address:"Krishnanagar",lat:23.4150,lng:88.5150,timings:"10 AM – 10 PM",theme:"Popular"},
{id:"bejikhali",name:"Bejikhali",area:"Krishnanagar",address:"Bejikhali",lat:23.4160,lng:88.5160,timings:"10 AM – 10 PM",theme:"Popular"},
{id:"nediarpara",name:"Nediarpara",area:"Krishnanagar",address:"Nediarpara",lat:23.4170,lng:88.5170,timings:"10 AM – 10 PM",theme:"Popular"},
{id:"baghadanga",name:"Baghadanga",area:"Krishnanagar",address:"Baghadanga",lat:23.4180,lng:88.5180,timings:"10 AM – 10 PM",theme:"Popular"},
{id:"patrabazar-smriti",name:"Patrabazar Smriti",area:"Krishnanagar",address:"Patrabazar",lat:23.4190,lng:88.5190,timings:"10 AM – 10 PM",theme:"Popular"},

// ── Wider Hooghly & Nadia ──
{id:"rishra",name:"Rishra Jagaddhatri Puja",area:"Rishra",address:"Rishra, Hooghly",lat:22.7200,lng:88.3500,timings:"10 AM – 10 PM",theme:"Vibrant community pujas"},
{id:"singur",name:"Singur Jagaddhatri Puja",area:"Singur",address:"Singur, Hooghly",lat:22.8100,lng:88.2300,timings:"10 AM – 10 PM",theme:"Traditional rituals"},
{id:"guptipara",name:"Guptipara Jagaddhatri Puja",area:"Guptipara",address:"Guptipara, Hooghly",lat:23.2000,lng:88.4500,timings:"10 AM – 10 PM",theme:"Barowari style"},
{id:"ichhapur",name:"Ichhapur Nawabgunj Jagaddhatri Puja",area:"Ichhapur",address:"Ichhapur Nawabgunj",lat:22.8100,lng:88.4200,timings:"10 AM – 10 PM",theme:"Five-day festival"},
{id:"tehatta",name:"Tehatta Jagaddhatri Puja",area:"Tehatta",address:"Tehatta, Nadia",lat:23.7200,lng:88.5500,timings:"10 AM – 10 PM",theme:"Detailed idols"},
{id:"ashoknagar",name:"Ashoknagar-Kalyangarh Jagaddhatri Puja",area:"Ashoknagar",address:"Ashoknagar-Kalyangarh",lat:22.8300,lng:88.6200,timings:"10 AM – 10 PM",theme:"Artistic pandals"},
{id:"howrah",name:"Howrah Jagaddhatri Puja",area:"Howrah",address:"Howrah",lat:22.5900,lng:88.3100,timings:"10 AM – 10 PM",theme:"Craftsmanship, local flavor"},
{id:"serampore",name:"Serampore Jagaddhatri Puja",area:"Serampore",address:"Serampore, Hooghly",lat:22.7500,lng:88.3400,timings:"10 AM – 10 PM",theme:"Colonial-era town puja"},
{id:"uttarpara",name:"Uttarpara Jagaddhatri Puja",area:"Uttarpara",address:"Uttarpara, Hooghly",lat:22.6700,lng:88.3500,timings:"10 AM – 10 PM",theme:"Community celebration"},
{id:"konnagar",name:"Konnagar Jagaddhatri Puja",area:"Konnagar",address:"Konnagar, Hooghly",lat:22.7000,lng:88.3500,timings:"10 AM – 10 PM",theme:"Community celebration"},
{id:"chinsurah",name:"Chinsurah Jagaddhatri Puja",area:"Chinsurah",address:"Chinsurah, Hooghly",lat:22.9000,lng:88.3900,timings:"10 AM – 10 PM",theme:"Dutch-era town puja"},
{id:"bandel",name:"Bandel Jagaddhatri Puja",area:"Bandel",address:"Bandel, Hooghly",lat:22.9300,lng:88.3800,timings:"10 AM – 10 PM",theme:"Community celebration"},
{id:"tarakeswar",name:"Tarakeswar Jagaddhatri Puja",area:"Tarakeswar",address:"Tarakeswar, Hooghly",lat:22.8900,lng:88.0200,timings:"10 AM – 10 PM",theme:"Pilgrim town puja"},
{id:"arambagh",name:"Arambagh Jagaddhatri Puja",area:"Arambagh",address:"Arambagh, Hooghly",lat:22.8800,lng:87.7800,timings:"10 AM – 10 PM",theme:"Community celebration"},
{id:"dhaniakhali",name:"Dhaniakhali Jagaddhatri Puja",area:"Dhaniakhali",address:"Dhaniakhali, Hooghly",lat:22.9700,lng:88.1000,timings:"10 AM – 10 PM",theme:"Weaver-town tradition"},
{id:"boinchi",name:"Boinchi Jagaddhatri Puja",area:"Boinchi",address:"Boinchi, Hooghly",lat:23.0500,lng:88.3000,timings:"10 AM – 10 PM",theme:"Notable celebration"},
{id:"sutragarh",name:"Sutragarh Jagaddhatri Puja",area:"Sutragarh",address:"Sutragarh, Hooghly",lat:22.9500,lng:88.3800,timings:"10 AM – 10 PM",theme:"Notable celebration"},
{id:"santipur",name:"Santipur Jagaddhatri Puja",area:"Santipur",address:"Santipur, Nadia",lat:23.2500,lng:88.4300,timings:"10 AM – 10 PM",theme:"Notable celebration"},
];