// js/names-bn.js
// Bengali display names for every pandal.
// Key = pandal.id from data.js · Value = Bengali name shown in the UI.
// Add a new line whenever a new pandal is added.

export const NAME_BN = {
  // ─── Chandannagar ───
  "haridradanga": "হরিদ্রাডাঙা",
  "silbagan": "শিলবাগান",
  "haridradanga-garerdhar-battala": "হরিদ্রাডাঙা গড়েরধার (বটতলা)",
  "bibirhat-charaktala": "বিবিরহাট চরকতলা",
  "bibirhat-charaktala-tematha": "বিবিরহাট চরকতলা তেমাথা",
  "boro-taldanga": "বড় টালডাঙা",
  "kabaripara": "কবরীপাড়া",
  "surerpukur": "সুরেরপুকুর",
  "surerpukur-garerdhar": "সুরেরপুকুর গড়েরধার",
  "boro-mitrabagan": "বড় মিত্রবাগান",
  "uttaranchal": "উত্তরাঞ্চল",
  "boro-dighirdhar": "বড় দীঘিরধার",
  "kundughat-uttar-purbanchal": "কুণ্ডুঘাট উত্তর পুর্বাঞ্চল",
  "kundughat": "কুণ্ডুঘাট",
  "kundughat-dalan": "কুণ্ডুঘাট দালান",
  "goswamighat": "গোস্বামীঘাট",
  "boro-panchanantala": "বড় পঞ্চাননতলা",
  "yuba-sampraday-boro-champatala": "বড় চাঁপাতলা",
  "kantapukur-chowmatha": "কাঁটাপুকুর চৌমাথা",
  "kantapukur": "কাঁটাপুকুর",
  "sauli": "সাউলি",
  "narua-sarkarpara": "নারুয়া সরকারপাড়া",
  "boro-kalitala-bylane": "বড় কালীতলা বাইলেন",
  "boro": "বড়",
  "boro-jadu-ghosh-lane": "বড় যদু ঘোষ লেন",
  "ghora-pukurdhar": "ঘোড়া পুকুরধার",
  "boro-kalitala": "বড় কালীতলা",
  "palpara": "পালপাড়া",
  "narua": "নারুয়া",
  "boraichanditala": "বরাইচণ্ডীতলা",
  "narua-boropukurdhar": "নারুয়া বড়পুকুরধার",
  "jompukurdhar": "জমপুকুরধার",
  "sarishapara": "সরিষাপাড়া",
  "dharapara": "ধাড়াপাড়া",
  "dharapara-bylane-tarun-sangha": "ধাড়াপাড়া বাইলেন তারুণ সংঘ",
  "helapukur": "হেলাপুকুর",
  "dharapara-mandirtala-madhyanchal": "ধাড়াপাড়া মন্দিরতলা (মধ্যঞ্চল)",
  "mollahazi-bagan": "মোল্লাহাজি বাগান",
  "surighat": "সুরিঘাট",
  "bindubasinipara": "বিন্দুবাসিনীপাড়া",
  "tantirbagan": "তাঁতিরবাগান",
  "balak-sampraday-ganj-neogi-bagan": "বালক সম্প্রদায় গঞ্জ নিয়োগীবাগান",
  "tantirbagan-charthakurtala": "তাঁতিরবাগান চারথাকুরতলা",
  "ganj-shitalatala": "গঞ্জ শীতলাতলা",
  "narua-shyamkhristan-bagan": "নারুয়া শ্যামখ্রিস্টান বাগান",
  "jagannathbati": "জগন্নাথবাটী",
  "laxmigunj-bazar": "লক্ষ্মীগঞ্জ বাজার",
  "laxmigunj-kaporepotti": "লক্ষ্মীগঞ্জ কাপড়েপট্টি",
  "laxmigunj-chaulpotti": "লক্ষ্মীগঞ্জ চাউলপট্টি",
  "laxmigunj-chowmatha": "লক্ষ্মীগঞ্জ চৌমাথা",
  "bidyalankar": "বিদ্যালঙ্কার",
  "kalupukur": "কালুপুকুর",
  "bhagar-more-chowmatha": "ভাগাড় মোড় চৌমাথা",
  "urdibazar-chunagoli": "উর্দিবাজার চুনাগলি",
  "chandni-benepukur": "চাঁদনী বেণেপুকুর",
  "talpukurdhar-sishu-udyan": "টালপুকুরধার শিশু উদ্যান",
  "bagbazar-talpukurdhar": "বাগবাজার টালপুকুরধার",
  "kalupukur-garerdhar": "কালুপুকুর গড়েরধার",
  "sitalatala-bauripara": "শীতলাতলা বাউরীপাড়া",
  "sramikpally-laldighir-dhar": "শ্রমিকপল্লী লালদীঘিরধার",
  "apanjan": "আপনজন",
  "bagbazar-babupukurdhar": "বাগবাজার বাবুপুকুরধার",
  "pilkhana-kuthirghat": "পিলখানা কুঠিরঘাট",
  "kuthir-math-north": "কুঠির মঠ (উত্তর)",
  "bagbazar-chowmatha": "বাগবাজার চৌমাথা",
  "madhyanchal": "মধ্যঞ্চল",
  "fatakgora": "ফটকগোড়া",
  "khalisani": "খালিশানী",
  "urdibazar": "উর্দিবাজার",
  "barabazar": "বারাবাজার",
  "bagbazar": "বাগবাজার",
  "suksanatantala-benepukurdhar": "সুক্ষ্মসনাতনতলা বেণেপুকুরধার",
  "baidyapota": "বৈদ্যাপোতা",
  "ashwatthatala-suksanatantala": "অশ্বত্থতলা সুক্ষ্মসনাতনতলা",
  "lalbagan": "লালবাগান",
  "padripara-farmadighi": "পাদ্রীপাড়া ফার্মাদীঘি",
  "lalbagan-padripara": "লালবাগান পাদ্রীপাড়া",
  "khalisani-garerdhar-tematha": "খালিশানী গড়েরধার তেমাথা",
  "hatkhola-nonatola": "হাটখোলা ন'নাতলা",
  "padripara": "পাদ্রীপাড়া",
  "halderpara-adi": "হালদারপাড়া (আদি)",
  "halderpara-sasthitala": "হালদারপাড়া ষষ্ঠীতলা",
  "padripara-kalitala": "পাদ্রীপাড়া কালীতলা",
  "rathersarak-sambala-shibtala": "রথেরসরক শামবলা শিবতলা",
  "duplexpatty-kultala": "ডুপ্লেক্সপট্টি কুলতলা",
  "duplexpatty": "ডুপ্লেক্সপট্টি",
  "hatkhola-bhubaneshwaritala": "হাটখোলা ভুবনেশ্বরীতলা",
  "hatkhola-mansatala": "হাটখোলা মনসাতলা",
  "hatkhola-daibakpara": "হাটখোলা দৈবকপাড়া",
  "sabinara": "সবিনারা",
  "kapalipara-sahebbagan": "কাপালীপাড়া সাহেববাগান",
  "binoy-badol-dinesh-sangha": "বিনয় বাদল দীনেশ সংঘ",
  "kanailal-pally": "কানাইলাল পল্লী",
  "beshohata": "বেশোহাটা",
  "gondalpara-notun-telighat": "গোণ্ডলপাড়া নতুন তেলিঘাট",
  "lichutala": "লিচুতলা",
  "mohila-samity": "মহিলা সমিতি",
  "gondalpara-charmandirtala": "গোণ্ডলপাড়া চারমন্দিরতলা",
  "gondalpara-kacharighat": "গোণ্ডলপাড়া কাছারিঘাট",
  "gondalpara-mansatala": "গোণ্ডলপাড়া মনসাতলা",
  "gondalpara-satghat": "গোণ্ডলপাড়া সাতঘাট",
  "adi-mahadanga": "আদি মহাদাঁগা",
  "agragati-ha-du-du-club": "অগ্রগতি হা-ডু-ডু ক্লাব",
  "subhas-sangha-mahadanga": "সুভাষ সংঘ মহাদাঁগা",
  "balak-sangha-mahadanga": "বালক সংঘ মহাদাঁগা",
  "gopalbag": "গোপালবাগ",
  "circusmath": "সার্কাসমঠ",
  "neogibagan": "নিয়োগীবাগান",
  "gondalpara-binodtala": "গোণ্ডলপাড়া বিনোদতলা",
  "gondalpara-moran-road": "গোণ্ডলপাড়া মোরান রোড",
  "gondalpara-radhanath-sikder-road-kadamtala": "গোণ্ডলপাড়া রাধানাথ শিকদার রোড কদমতলা",
  "gondalpara-a-c-chatterjee-lane": "গোণ্ডলপাড়া এ. সি. চ্যাটার্জী লেন",
  "ambika-athletic-club": "অম্বিকা অ্যাথলেটিক ক্লাব",
  "tematha": "তেমাথা",
  "charabagan-balak-samity": "চারাবাগান বালক সমিতি",
  "natunpara": "নতুনপাড়া",
  "harerpukurdhar": "হরেরপুকুরধার",
  "subhas-jagaran-sangha-tematha": "সুভাষ জাগরণ সংঘ তেমাথা",
  "aurobinda-sangha-barasat": "অরবিন্দ সংঘ বরাসাত",
  "barasat-chakrabartypara": "বরাসাত চক্রবর্তীপাড়া",
  "barasat-banerjeepara-madhyanchal": "বরাসাত ব্যানার্জীপাড়া মধ্যঞ্চল",
  "barasat-banerjeepara": "বরাসাত ব্যানার্জীপাড়া",
  "barasat-dakshin": "বরাসাত দক্ষিণ",
  "dinemardanga-talpukurdhar": "দিনেমারদাঁগা টালপুকুরধার",
  "gondalpara-kabadi-club": "গোণ্ডলপাড়া কাবাডি ক্লাব",
  "dinemardanga-amtala": "দিনেমারদাঁগা আমতলা",
  "dinemardanga-panchapandab": "দিনেমারদাঁগা পঞ্চপাণ্ডব",
  "barasat-gate": "বরাসাত গেট",
  "dashabhujatala": "দশভুজাতলা",
  "dinemardanga-shibmandir": "দিনেমারদাঁগা শিবমন্দির",
  "dinemardanga-pratik-sangha": "দিনেমারদাঁগা প্রতীক সংঘ",
  "balak-samity-garerdhar": "বালক সমিতি গড়েরধার",

  // ─── Bhadreswar ───
  "brahminpara-jagarani-samity": "ব্রাহ্মণপাড়া জাগরণী সমিতি",
  "subhaspally": "সুভাষপল্লী",
  "khalisani-kalpukurdhar": "খালিশানী কালুপুকুরধার",
  "bowbazar-sitalatala": "বউবাজার শীতলাতলা",
  "khalisani-bowbazar": "খালিশানী বউবাজার",
  "swetpur": "শ্বেতপুর",
  "puroshree": "পুরশ্রী",
  "nabagram-puroshree": "নবগ্রাম পুরশ্রী",
  "mankundu": "মানকুণ্ডু",
  "mankundu-tentultala": "মানকুণ্ডু তেঁতুলতলা",
  "adi-palpara": "আদি পালপাড়া",
  "mankundu-goldighirdhar": "মানকুণ্ডু গোলদীঘিরধার",
  "bhadreswar-krisnapatty-sastitala-dakhinachal": "ভদ্রেশ্বর কৃষ্ণপট্টি শাস্তীতলা দক্ষিণাঞ্চল",
  "telinipara-baburbazar": "তেলিনীপাড়া বাবুরবাজার",
  "telinipara-kalitala": "তেলিনীপাড়া কালীতলা",
  "tantipara-sabuj-sangha": "তাঁতিপাড়া সবুজ সংঘ",
  "telinipara-kultala": "তেলিনীপাড়া কুলতলা",
  "telinipara-annapurna-barowari": "তেলিনীপাড়া অন্নপূর্ণা বরোয়ারী",
  "telinipara-neheru-bidyapith": "তেলিনীপাড়া নেহেরু বিদ্যাপীঠ",
  "telinipara-rajabazar": "তেলিনীপাড়া রাজাবাজার",
  "krishnapatty": "কৃষ্ণপট্টি",
  "joy-bharat-sangha-chandrababur-bazar": "জয় ভারত সংঘ (চন্দ্রবাবুর বাজার)",
  "bhadreswar-yuvak-samity": "ভদ্রেশ্বর যুবক সমিতি",
  "maniknagar": "মণিকনগর",
  "kishore-samity-palbagan": "কিশোর সমিতি পালবাগান",
  "bethpukurdhar": "বেঠপুকুরধার",
  "bhadreswar-nimtala": "ভদ্রেশ্বর নিমতলা",
  "kheyali-sangha": "খেয়ালী সংঘ",
  "bhadreswar-chaldatala": "ভদ্রেশ্বর চালদাতলা",
  "bhadreswar-station-road-chowmatha": "ভদ্রেশ্বর স্টেশন রোড চৌমাথা",
  "bhadreswar-ganj": "ভদ্রেশ্বর গঞ্জ",
  "koyedbeltala-balok-sangha": "কোয়েডবেলতলা বালক সংঘ",
  "bhadreswar-station-road-haritokitala": "ভদ্রেশ্বর স্টেশন রোড হরিতকীতলা",
  "bibeknagar-amratala-bhadreswar-station-road": "বিবেকনগর অমৃততলা স্টেশন রোড",
  "yuva-chetana-jpc-park-maidan-gov-colony": "যুব চেতনা জেপিসি পার্ক ময়দান গভ. কলোনী",
  "nimtala-sporting-club": "নিমতলা স্পোর্টিং ক্লাব",
  "pradip-sangha-library-road": "প্রদীপ সংঘ লাইব্রেরী রোড",
  "gourhati-tetultala": "গোঁড়হাটি তেঁতুলতলা",
  "naba-sangha-library-road": "নব সংঘ লাইব্রেরী রোড",
  "youth-corner-library-road": "ইয়ুথ কর্নার লাইব্রেরী রোড",
  "bhadreshwar-station-road-byabsayi-samity": "ভদ্রেশ্বর স্টেশন রোড ব্যয়সায়ী সমিতি",
  "bhadreswar-15-pally": "ভদ্রেশ্বর ১৫ পল্লী",
  "bhadreswar-jagadhatri-sporting-club": "ভদ্রেশ্বর জগদ্ধাত্রী স্পোর্টিং ক্লাব",
  "angus": "অ্যাঙ্গাস",
  "subhaspally-uttarpara": "সুভাষপল্লী উত্তরপাড়া",
  "milannagar-sohid-bedi-mankundu": "মিলননগর শহীদ বেদী মানকুণ্ডু",
  "sukantanagar-mahila-samity": "সুকান্তনগর মহিলা সমিতি",
};
